### ISSUE TITLE
Program crashes when subject line hard limit is exceeded

### ISSUE THREAD

**Issue by lyckberg** [simonlindberg/commit-check#1]
The misspelled variable name makes the checker crash instead of quitting gracefully if the subject lines hard limit were exceeded. `SUBJECT_LINE_LENGTH_HAD_LIMIT` in the function `assert_subject_length` should be `SUBJECT_LINE_LENGTH_HARD_LIMIT`.

**Comment by simonlindberg** [comment]
Sorry about that, fix it for you.

And remember kids, don't refactor code in a hurry!
